### PR TITLE
Copy PID

### PR DESCRIPTION
**Pull request by ruixiong**

### CODE REVIEW

**Comment by thorntonjn** [comment]
I'll let @skye2k2 review this.

**Comment by thorntonjn** [comment]
Unit tests for the stackoverflow code seems could come later so that we can get a fix out quickly.

**Comment by ruixiong** [comment]
no~ that was supposed to be removed. I will fix that right now.

**Comment by ruixiong** [comment]
oh okay~ haha that makes sense~ give me 2 min.

**Comment by ruixiong** [comment]
I see. working on it now.

**Comment by ruixiong** [comment]
Thank you!

**Pull request merged**
