### PR TITLE
Added icons for each of the tree views

### PR DESCRIPTION
**Pull request by dthorne**

### CODE REVIEW

**Comment by skye2k2** [comment]
Can we please rebase and merge, from now on?

**Comment by thorntonjn** [comment]
Sure. Is that what everyone has decided for v8 ?  I actually prefer rebase and merge to preserve better history, but with this pull wasn't there just one commit ?    My only concern is that most of the people I have worked with have said they prefer the squash and merge.

**Comment by skye2k2** [comment]
When you **merge**, _you_ show up as the committer in our Slack notifications with the unhelpful message: "Merge pull request {number} from {branch_name}, instead of the original author and message that actually tells you what changed in that build. Then you permanently have _two_ entries in your git history for that one change.

**Squashing** is appropriate when the commits go something like: 

- "Modify component x to handle new parameters"
- "Update unit tests"
- "Fix broken build"
- "Trying another way to fix build"
- "Re-add logic that apparently needed to be there"
- "Appeasing Code Climate"
- "Finally cutting new release"

Because the flailing commits will all be mashed into the resulting "Modify component x to handle new parameters" commit. Good practice.

Only on rare occasions, most commonly with long-lived branches, will you want to do a plain merge, because squashing would lose valuable history in the transformation of the code or reduce a contributor's man-month of effort into a single contribution. But _never_ for a single commit.

**Comment by thorntonjn** [comment]
I see what you are saying.  For me, I also don't wan't to squash my individual commits because I like seeing the individual commits build on each other.  I like to squash only the flailing ones ahead of time.  But for a pull with lots of commits the individual ones become more important.  A single small commit is more easily understood when going back in history.

**Comment by thorntonjn** [comment]
Oh, sorry this was my bad.  I didn't mean to ever do a **Merge** .   I meant to do a Squash and Merge.  That's why the two commit messages showed up.  I didn't realize this was a new repo I hadn't previously commited to.

Our team generally prefers the Squash and Merge as opposed to the Rebase and Merge.  The rebase adds all the individual commits to the github history and most of the devs don't need that.  They prefer a single commit with all of the messages appended into the message.

**Pull request merged**
